Create DATABASE IF NOT EXISTS SAAS_DB;
CREATE SCHEMA IF NOT EXISTS SAAS_DB.ANALYTICS;
USE SCHEMA  SAAS_DB.ANALYTICS;

CREATE OR REPLACE TABLE SAAS_DB.ANALYTICS.CUSTOMER_CHURN(
    CUSTOMER_ID VARCHAR(50),
    SIGNUP_DATE DATE,
    CHURN_DATE DATE,
    SUBSCRIPTION_PLAN VARCHAR(20),
    CONTRACT_TYPE VARCHAR(20),
    MONTHLY_FEE NUMBER(10, 2),
    SUPPORT_TICKETS NUMBER,
    USAGE_HOURS FLOAT
);

USE SCHEMA SAAS_DB.ANALYTICS;

CREATE OR REPLACE TABLE SAAS_DB.ANALYTICS.PAYMENTS (
    PAYMENT_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(50),
    PAYMENT_DATE DATE,
    AMOUNT NUMBER(10, 2),
    PAYMENT_STATUS VARCHAR(20)
);

CREATE OR REPLACE TABLE SAAS_DB.ANALYTICS.SUPPORT_TICKETS_LOG (
    TICKET_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(50),
    TICKET_DATE DATE,
    CATEGORY VARCHAR(50),
    RESOLUTION_TIME_HOURS FLOAT,
    SATISFACTION_SCORE NUMBER
);

SELECT 'CUSTOMER_CHURN' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM SAAS_DB.ANALYTICS.CUSTOMER_CHURN
UNION ALL
SELECT 'PAYMENTS', COUNT(*) FROM SAAS_DB.ANALYTICS.PAYMENTS
UNION ALL
SELECT 'SUPPORT_TICKETS_LOG', COUNT(*) FROM SAAS_DB.ANALYTICS.SUPPORT_TICKETS_LOG;
